# Generated by Django 5.0.7 on 2025-12-19 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollen62App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категориии'},
        ),
    ]
